package com.ummar.inventorymanagement.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
public class Inbound {
    private @Id @GeneratedValue Long id;

    @Column(unique = true)
    private String autoGeneratedReference;
    
    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    private Long quantity;

    @ManyToOne
    @JoinColumn(name = "storage_id", nullable = false)
    private Storage storage;

    private LocalDateTime timestampReceived;

    Inbound() {
        this.autoGeneratedReference = UUID.randomUUID().toString();
        this.timestampReceived = LocalDateTime.now();
    }

    Inbound(Product product, Long quantity, Storage storage) {
        this.autoGeneratedReference = UUID.randomUUID().toString();
        this.product = product;
        this.quantity = quantity;
        this.storage = storage;
        this.timestampReceived = LocalDateTime.now();
    }

    public Long getId() {
        return this.id;
    }

    public String getAutoGeneratedReference() {
        return this.autoGeneratedReference;
    }
    
    public Product getProduct() {
        return this.product;
    }

    public Long getQuantity() {
        return this.quantity;
    }

    public Storage getStorage() {
        return this.storage;
    }

    public LocalDateTime getTimestampShipped() {
        return this.timestampReceived;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setAutoGeneratedReference(String autoGeneratedReference) {
        this.autoGeneratedReference = autoGeneratedReference;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public void setStorage(Storage storage) {
        this.storage = storage;
    }

    public void setTimestampShipped(LocalDateTime timestampReceived) {
        this.timestampReceived = timestampReceived;
    }
}
