package com.ummar.inventorymanagement.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
public class Outbound {
    private @Id @GeneratedValue Long id;
    private String autoGeneratedReference;
    
    @ManyToOne
    private Product product;
    
    private Long quantity;
    private String destination;
    private LocalDateTime timestampShipped;

    Outbound() {
        this.autoGeneratedReference = UUID.randomUUID().toString();
        this.timestampShipped = LocalDateTime.now();
    }

    Outbound(Product product, Long quantity, String destination) {
        this.autoGeneratedReference = UUID.randomUUID().toString();
        this.product = product;
        this.quantity = quantity;
        this.destination = destination;
        this.timestampShipped = LocalDateTime.now();
    }

    public Long getId() {
        return this.id;
    }

    public String getAutoGeneratedReference() {
        return this.autoGeneratedReference;
    }
    
    public Product getProduct() {
        return this.product;
    }

    public Long getQuantity() {
        return this.quantity;
    }

    public String getDestination() {
        return this.destination;
    }

    public LocalDateTime getTimestampShipped() {
        return this.timestampShipped;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setAutoGeneratedReference(String autoGeneratedReference) {
        this.autoGeneratedReference = autoGeneratedReference;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    public void setTimestampShipped(LocalDateTime timestampShipped) {
        this.timestampShipped = timestampShipped;
    }
}
